version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.27
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: postgres-db
            port: 5432
            user: ${DB_USER}
            password: ${DB_PASSWORD}
            migrations: true
            rawAccess: true
  postgres-db:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
